testing new generate script for buttons and LEDs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,10 +2,16 @@ name: Zephyr CI
 
 on:
   push:
+    # paths:
+    #   - 'led_tests/**'
+    #   - 'led_button_tests/**'
   pull_request:
+    # paths:
+    #   - 'led_tests/**'
+    #   - 'led_button_tests/**'
 
 jobs:
-  build-and-test:
+  led_tests:
     runs-on: ubuntu-latest
     container:
       image: hardwario/nrf-connect-sdk-build:v2.9.0-1
@@ -24,35 +30,87 @@ jobs:
             $NATIVE_OVERLAY
           cat led_tests/native_sim.overlay
 
-      # 3. Initialize west
-      - name: West init
-        run: |
-          cd led_tests
-          west init
-          west update -o=--depth=1 -n
+      # # 3. Initialize west
+      # - name: West init
+      #   run: |
+      #     cd led_tests
+      #     west init
+      #     west update -o=--depth=1 -n
 
-      # 4. Build for native_sim using both overlays
-      - name: Build for native_sim
-        run: |
-          cd led_tests
-          west build -b native_sim -- \
-            -DDTC_OVERLAY_FILE=native_sim.overlay
+      # # 4. Build for native_sim using both overlays
+      # - name: Build for native_sim
+      #   run: |
+      #     cd led_tests
+      #     west build -b native_sim -- \
+      #       -DDTC_OVERLAY_FILE=native_sim.overlay
 
-      # 5. Run the simulation and capture output
-      - name: Run simulation
-        run: |
-          cd led_tests
-          chmod +x build/zephyr/zephyr.exe
-          timeout 10s stdbuf -oL build/zephyr/zephyr.exe | tee simulation_output.log
+      # # 5. Run the simulation and capture output
+      # - name: Run simulation
+      #   run: |
+      #     cd led_tests
+      #     chmod +x build/zephyr/zephyr.exe
+      #     timeout 10s stdbuf -oL build/zephyr/zephyr.exe | tee simulation_output.log
 
-      # 6. Check that LEDs turned on/off
-      - name: Check LED/button output
+      # # 6. Check that LEDs turned on/off
+      # - name: Check LED/button output
+      #   run: |
+      #     cd led_tests
+      #     cat simulation_output.log
+      #     if grep -q "LED ON" simulation_output.log && grep -q "LED OFF" simulation_output.log; then
+      #         echo "LED toggled correctly!"
+      #     else
+      #         echo "LED did not toggle correctly!"
+      #         exit 1
+      #     fi
+
+      # # - name: Upload simulation log
+      # #   if: failure()
+      # #   uses: actions/upload-artifact@v4
+      # #   with:
+      # #     name: simulation-log
+      # #     path: led_tests/simulation_output.log
+
+  led-button-tests:
+    runs-on: ubuntu-latest
+    container:
+      image: hardwario/nrf-connect-sdk-build:v2.9.0-1
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Generate temporary native_sim overlay
         run: |
-          cd led_tests
-          cat simulation_output.log
-          if grep -q "LED ON" simulation_output.log && grep -q "LED OFF" simulation_output.log; then
-              echo "LED toggled correctly!"
-          else
-              echo "LED did not toggle correctly!"
-              exit 1
-          fi
+          NATIVE_OVERLAY="led_button_tests/native_sim.overlay"
+          python3 scripts/generate_overlay.py \
+            led_button_tests/boards/native_posix.overlay \
+            $NATIVE_OVERLAY
+          cat led_button_tests/native_sim.overlay
+
+      # - name: West init
+      #   run: |
+      #     cd led_button_tests
+      #     west init
+      #     west update -o=--depth=1 -n
+
+      # - name: Build for native_sim
+      #   run: |
+      #     cd led_button_tests
+      #     west build -b native_sim -- \
+      #       -DDTC_OVERLAY_FILE=native_sim.overlay
+
+      # - name: Run simulation
+      #   run: |
+      #     cd led_button_tests
+      #     chmod +x build/zephyr/zephyr.exe
+      #     # timeout 10s stdbuf -oL build/zephyr/zephyr.exe | tee simulation_output.log
+
+      # - name: Check LED + button output
+      #   run: |
+      #     cd led_button_tests
+      #     if grep -q "BUTTON PRESSED" simulation_output.log; then
+      #       echo "Button test passed!"
+      #     else
+      #       echo "Button test failed!"
+      #       exit 1
+      #     fi
