adding smf lab, testing ci pipeline artifact change

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,7 @@ jobs:
     outputs:
       gpio: ${{ steps.filter.outputs.gpio }}
       kernel: ${{ steps.filter.outputs.kernel }}
+      smf: ${{ steps.filter.outputs.smf }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -23,9 +24,36 @@ jobs:
               - 'lab_gpio/**'
             kernel:
               - 'lab_kernel/**'
+            smf:
+              - 'lab_smf/**'
+  
+  zephyr_setup:
+    runs-on: ubuntu-latest
+    container:
+      image: hardwario/nrf-connect-sdk-build:v2.9.0-1
+    
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+      - name: West init
+        run: |
+          cd lab_gpio
+          west init -m https://github.com/zephyrproject-rtos/zephyr --mr v3.7.0
+          west update -o=--depth=1 -n
+      
+      - name: Archive workspace
+        run: |
+          tar -czf zephyr_workspace.tar.gz zephyrproject .west
+      
+      - name: Upload workspace
+        uses: actions/upload-artifact@v4
+        with:
+          name: zephyr-workspace
+          path: zephyr_workspace.tar.gz
   
   gpio_tests:
-    needs: changes
+    needs: [changes, zephyr_setup]
     if: needs.changes.outputs.gpio == 'true'
     runs-on: ubuntu-latest
     container:
@@ -101,7 +129,7 @@ jobs:
           fi
   
   kernel_tests:
-    needs: changes
+    needs: [changes, zephyr_setup]
     if: needs.changes.outputs.kernel == 'true'
     runs-on: ubuntu-latest
     container:
@@ -176,3 +204,84 @@ jobs:
       #       echo "Could not determine test status"
       #       exit 1
       #     fi
+  
+  smf_tests:
+    needs: [changes, zephyr_setup]
+    if: needs.changes.outputs.smf == 'true'
+    runs-on: ubuntu-latest
+    container:
+      image: hardwario/nrf-connect-sdk-build:v2.9.0-1
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+      - name: Download workspace
+        uses: actions/download-artifact@v4
+        with:
+          name: zephyr-workspace
+      
+      - name: Extract workspace
+        run: |
+          tar -xzf zephyr_workspace.tar.gz
+      
+      # - name: Check code specs
+      #   run: |
+      #     set -e
+      #     cd lab_smf
+      #     grep -Eq '#define[[:space:]]+LED_BLINK_FREQ_HZ[[:space:]]+2' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_UP_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_DOWN_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq 'heartbeat_led' src/main.c
+      #     grep -Eq 'iv_pump_led' src/main.c
+      #     grep -Eq 'buzzer_led' src/main.c
+      #     grep -Eq 'error_led' src/main.c
+      #     grep -Eq 'sleep_button' src/main.c
+      #     grep -Eq 'freq_up_button' src/main.c
+      #     grep -Eq 'freq_down_button' src/main.c
+      #     grep -Eq 'reset_button' src/main.c
+      #     grep -Eq 'heartbeat' boards/native_posix.overlay
+      #     grep -Eq 'ivpump' boards/native_posix.overlay
+      #     grep -Eq 'buzzer' boards/native_posix.overlay
+      #     grep -Eq 'error' boards/native_posix.overlay
+      #     grep -Eq 'sleepbutton' boards/native_posix.overlay
+      #     grep -Eq 'frequpbutton' boards/native_posix.overlay
+      #     grep -Eq 'freqdownbutton' boards/native_posix.overlay
+      #     grep -Eq 'resetbutton' boards/native_posix.overlay
+      #     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!echo TODO based on this lab's spec
+      
+      - name: Build for native_sim
+        run: |
+          cd lab_smf
+          west build -b native_sim -- \
+            -DEXTRA_CONF_FILE=sim.prj.conf
+      
+      # - name: Build tests for native_sim
+      #   run: |
+      #     cd lab_smf
+      #     west build -b native_sim --build-dir=build_test -- \
+      #       -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
+      #       -DEXTRA_CONF_FILE=test.prj.conf \
+      #       -DTEST_BUILD=ON
+      
+      # - name: Run unit tests
+      #   run: |
+      #     cd lab_smf
+      #     chmod +x build_test/zephyr/zephyr.exe
+      #     build_test/zephyr/zephyr.exe | tee test_output.log
+          
+      # - name: Check test results
+      #   run: |
+      #     cd lab_smf
+      #     cat test_output.log
+      #     if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
+      #       echo "All tests passed!"
+      #       exit 0
+      #     elif grep -q "PROJECT EXECUTION FAILED" test_output.log; then
+      #       echo "Tests failed!"
+      #       exit 1
+      #     else
+      #       echo "Could not determine test status"
+      #       exit 1
+      #     fi
+
