code for each stage, updated ci file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,11 +11,15 @@ jobs:
       gpio: ${{ steps.filter.outputs.gpio }}
       kernel: ${{ steps.filter.outputs.kernel }}
       smf: ${{ steps.filter.outputs.smf }}
-      adc: ${{ steps.filter.outputs.adc }}
+      adc_single: ${{ steps.filter.outputs.adc_single }}
+      adc_buffered: ${{ steps.filter.outputs.adc_buffered }}
+      adc_async: ${{ steps.filter.outputs.adc_async }}
       any: ${{ steps.filter.outputs.gpio == 'true' ||
                steps.filter.outputs.kernel == 'true' ||
                steps.filter.outputs.smf == 'true' ||
-               steps.filter.outputs.adc == 'true'
+               steps.filter.outputs.adc_single == 'true' ||
+               steps.filter.outputs.adc_buffered == 'true' ||
+               steps.filter.outputs.adc_async == 'true'
             }}
     steps:
       - name: Checkout repository
@@ -32,8 +36,12 @@ jobs:
               - 'lab_kernel/**'
             smf:
               - 'lab_smf/**'
-            adc:
-              - 'lab_adc/**'
+            adc_single:
+              - 'lab_adc_single/**'
+            adc_buffered:
+              - 'lab_adc_buffered/**'
+            adc_async:
+              - 'lab_adc_async/**'
   
   zephyr_setup:
     needs: changes
@@ -300,9 +308,9 @@ jobs:
       #       exit 1
       #     fi
   
-  adc_tests:
+  adc_single_tests:
     needs: [changes, zephyr_setup]
-    if: needs.changes.outputs.adc == 'true'
+    if: needs.changes.outputs.adc_single == 'true'
     runs-on: ubuntu-latest
     container:
       image: hardwario/nrf-connect-sdk-build:v2.9.0-1
@@ -323,7 +331,7 @@ jobs:
       # - name: Check code specs
       #   run: |
       #     set -e
-      #     cd lab_adc
+      #     cd lab_adc_single
       #     grep -Eq '#define[[:space:]]+LED_BLINK_FREQ_HZ[[:space:]]+2' src/main.c
       #     grep -Eq '#define[[:space:]]+FREQ_UP_INC_HZ[[:space:]]+1' src/main.c
       #     grep -Eq '#define[[:space:]]+FREQ_DOWN_INC_HZ[[:space:]]+1' src/main.c
@@ -347,13 +355,13 @@ jobs:
       
       - name: Build for native_sim
         run: |
-          cd lab_adc
+          cd lab_adc_single
           west build -b native_sim -- \
             -DEXTRA_CONF_FILE=sim.prj.conf
       
       - name: Build tests for native_sim
         run: |
-          cd lab_adc
+          cd lab_adc_single
           west build -b native_sim --build-dir=build_test -- \
             -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
             -DEXTRA_CONF_FILE=test.prj.conf \
@@ -361,13 +369,173 @@ jobs:
       
       - name: Run unit tests
         run: |
-          cd lab_adc
+          cd lab_adc_single
           chmod +x build_test/zephyr/zephyr.exe
           build_test/zephyr/zephyr.exe | tee test_output.log
           
       - name: Check test results
         run: |
-          cd lab_adc
+          cd lab_adc_single
+          cat test_output.log
+          if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
+            echo "All tests passed!"
+            exit 0
+          elif grep -q "PROJECT EXECUTION FAILED" test_output.log; then
+            echo "Tests failed!"
+            exit 1
+          else
+            echo "Could not determine test status"
+            exit 1
+          fi
+
+  adc_buffered_tests:
+    needs: [changes, zephyr_setup]
+    if: needs.changes.outputs.adc_buffered == 'true'
+    runs-on: ubuntu-latest
+    container:
+      image: hardwario/nrf-connect-sdk-build:v2.9.0-1
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+      - name: Download workspace
+        uses: actions/download-artifact@v4
+        with:
+          name: zephyr-workspace
+      
+      - name: Extract workspace
+        run: |
+          tar -xzf zephyr_workspace.tar.gz
+      
+      # - name: Check code specs
+      #   run: |
+      #     set -e
+      #     cd lab_adc_buffered
+      #     grep -Eq '#define[[:space:]]+LED_BLINK_FREQ_HZ[[:space:]]+2' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_UP_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_DOWN_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq 'heartbeat_led' src/main.c
+      #     grep -Eq 'iv_pump_led' src/main.c
+      #     grep -Eq 'buzzer_led' src/main.c
+      #     grep -Eq 'error_led' src/main.c
+      #     grep -Eq 'sleep_button' src/main.c
+      #     grep -Eq 'freq_up_button' src/main.c
+      #     grep -Eq 'freq_down_button' src/main.c
+      #     grep -Eq 'reset_button' src/main.c
+      #     grep -Eq 'heartbeat' boards/native_posix.overlay
+      #     grep -Eq 'ivpump' boards/native_posix.overlay
+      #     grep -Eq 'buzzer' boards/native_posix.overlay
+      #     grep -Eq 'error' boards/native_posix.overlay
+      #     grep -Eq 'sleepbutton' boards/native_posix.overlay
+      #     grep -Eq 'frequpbutton' boards/native_posix.overlay
+      #     grep -Eq 'freqdownbutton' boards/native_posix.overlay
+      #     grep -Eq 'resetbutton' boards/native_posix.overlay
+      #      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!echo TODO based on this lab's spec
+      
+      - name: Build for native_sim
+        run: |
+          cd lab_adc_buffered
+          west build -b native_sim -- \
+            -DEXTRA_CONF_FILE=sim.prj.conf
+      
+      - name: Build tests for native_sim
+        run: |
+          cd lab_adc_buffered
+          west build -b native_sim --build-dir=build_test -- \
+            -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
+            -DEXTRA_CONF_FILE=test.prj.conf \
+            -DTEST_BUILD=ON
+      
+      - name: Run unit tests
+        run: |
+          cd lab_adc_buffered
+          chmod +x build_test/zephyr/zephyr.exe
+          build_test/zephyr/zephyr.exe | tee test_output.log
+          
+      - name: Check test results
+        run: |
+          cd lab_adc_buffered
+          cat test_output.log
+          if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
+            echo "All tests passed!"
+            exit 0
+          elif grep -q "PROJECT EXECUTION FAILED" test_output.log; then
+            echo "Tests failed!"
+            exit 1
+          else
+            echo "Could not determine test status"
+            exit 1
+          fi
+
+  adc_async_tests:
+    needs: [changes, zephyr_setup]
+    if: needs.changes.outputs.adc_async == 'true'
+    runs-on: ubuntu-latest
+    container:
+      image: hardwario/nrf-connect-sdk-build:v2.9.0-1
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+      - name: Download workspace
+        uses: actions/download-artifact@v4
+        with:
+          name: zephyr-workspace
+      
+      - name: Extract workspace
+        run: |
+          tar -xzf zephyr_workspace.tar.gz
+      
+      # - name: Check code specs
+      #   run: |
+      #     set -e
+      #     cd lab_adc_async
+      #     grep -Eq '#define[[:space:]]+LED_BLINK_FREQ_HZ[[:space:]]+2' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_UP_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_DOWN_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq 'heartbeat_led' src/main.c
+      #     grep -Eq 'iv_pump_led' src/main.c
+      #     grep -Eq 'buzzer_led' src/main.c
+      #     grep -Eq 'error_led' src/main.c
+      #     grep -Eq 'sleep_button' src/main.c
+      #     grep -Eq 'freq_up_button' src/main.c
+      #     grep -Eq 'freq_down_button' src/main.c
+      #     grep -Eq 'reset_button' src/main.c
+      #     grep -Eq 'heartbeat' boards/native_posix.overlay
+      #     grep -Eq 'ivpump' boards/native_posix.overlay
+      #     grep -Eq 'buzzer' boards/native_posix.overlay
+      #     grep -Eq 'error' boards/native_posix.overlay
+      #     grep -Eq 'sleepbutton' boards/native_posix.overlay
+      #     grep -Eq 'frequpbutton' boards/native_posix.overlay
+      #     grep -Eq 'freqdownbutton' boards/native_posix.overlay
+      #     grep -Eq 'resetbutton' boards/native_posix.overlay
+      #      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!echo TODO based on this lab's spec
+      
+      - name: Build for native_sim
+        run: |
+          cd lab_adc_async
+          west build -b native_sim -- \
+            -DEXTRA_CONF_FILE=sim.prj.conf
+      
+      - name: Build tests for native_sim
+        run: |
+          cd lab_adc_async
+          west build -b native_sim --build-dir=build_test -- \
+            -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
+            -DEXTRA_CONF_FILE=test.prj.conf \
+            -DTEST_BUILD=ON
+      
+      - name: Run unit tests
+        run: |
+          cd lab_adc_async
+          chmod +x build_test/zephyr/zephyr.exe
+          build_test/zephyr/zephyr.exe | tee test_output.log
+          
+      - name: Check test results
+        run: |
+          cd lab_adc_async
           cat test_output.log
           if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
             echo "All tests passed!"
