updating ci pipeline, rerunning gpio

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,9 +20,9 @@ jobs:
         with:
           filters: |
             gpio:
-              - 'gpio_lab/**'
+              - 'lab_gpio/**'
             kernel:
-              - 'kernel_lab/**'
+              - 'lab_kernel/**'
   
   gpio_tests:
     needs: changes
@@ -37,14 +37,14 @@ jobs:
       
       - name: West init
         run: |
-          cd gpio_lab
+          cd lab_gpio
           west init -m https://github.com/zephyrproject-rtos/zephyr --mr v3.7.0
           west update -o=--depth=1 -n
       
       - name: Check code specs
         run: |
           set -e
-          cd gpio_lab
+          cd lab_gpio
           grep -Eq '#define[[:space:]]+LED_BLINK_FREQ_HZ[[:space:]]+2' src/main.c
           grep -Eq '#define[[:space:]]+FREQ_UP_INC_HZ[[:space:]]+1' src/main.c
           grep -Eq '#define[[:space:]]+FREQ_DOWN_INC_HZ[[:space:]]+1' src/main.c
@@ -67,13 +67,13 @@ jobs:
       
       - name: Build for native_sim
         run: |
-          cd gpio_lab
+          cd lab_gpio
           west build -b native_sim -- \
             -DEXTRA_CONF_FILE=sim.prj.conf
       
       - name: Build tests for native_sim
         run: |
-          cd gpio_lab
+          cd lab_gpio
           west build -b native_sim --build-dir=build_test -- \
             -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
             -DEXTRA_CONF_FILE=test.prj.conf \
@@ -81,13 +81,13 @@ jobs:
       
       - name: Run unit tests
         run: |
-          cd gpio_lab
+          cd lab_gpio
           chmod +x build_test/zephyr/zephyr.exe
           build_test/zephyr/zephyr.exe | tee test_output.log
           
       - name: Check test results
         run: |
-          cd gpio_lab
+          cd lab_gpio
           cat test_output.log
           if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
             echo "All tests passed!"
@@ -113,47 +113,66 @@ jobs:
       
       - name: West init
         run: |
-          cd kernel_lab
+          cd lab_kernel
           west init -m https://github.com/zephyrproject-rtos/zephyr --mr v3.7.0
           west update -o=--depth=1 -n
       
-      - name: Check code specs
-        run: |
-          set -e
-          cd kernel_lab
-          echo TODO
+      # - name: Check code specs
+      #   run: |
+      #     set -e
+      #     cd lab_kernel
+      #     grep -Eq '#define[[:space:]]+LED_BLINK_FREQ_HZ[[:space:]]+2' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_UP_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq '#define[[:space:]]+FREQ_DOWN_INC_HZ[[:space:]]+1' src/main.c
+      #     grep -Eq 'heartbeat_led' src/main.c
+      #     grep -Eq 'iv_pump_led' src/main.c
+      #     grep -Eq 'buzzer_led' src/main.c
+      #     grep -Eq 'error_led' src/main.c
+      #     grep -Eq 'sleep_button' src/main.c
+      #     grep -Eq 'freq_up_button' src/main.c
+      #     grep -Eq 'freq_down_button' src/main.c
+      #     grep -Eq 'reset_button' src/main.c
+      #     grep -Eq 'heartbeat' boards/native_posix.overlay
+      #     grep -Eq 'ivpump' boards/native_posix.overlay
+      #     grep -Eq 'buzzer' boards/native_posix.overlay
+      #     grep -Eq 'error' boards/native_posix.overlay
+      #     grep -Eq 'sleepbutton' boards/native_posix.overlay
+      #     grep -Eq 'frequpbutton' boards/native_posix.overlay
+      #     grep -Eq 'freqdownbutton' boards/native_posix.overlay
+      #     grep -Eq 'resetbutton' boards/native_posix.overlay
+      #     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!echo TODO based on this lab's spec
       
       - name: Build for native_sim
         run: |
-          cd kernel_lab
+          cd lab_kernel
           west build -b native_sim -- \
             -DEXTRA_CONF_FILE=sim.prj.conf
       
-      - name: Build tests for native_sim
-        run: |
-          cd kernel_lab
-          west build -b native_sim --build-dir=build_test -- \
-            -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
-            -DEXTRA_CONF_FILE=test.prj.conf \
-            -DTEST_BUILD=ON
+      # - name: Build tests for native_sim
+      #   run: |
+      #     cd lab_kernel
+      #     west build -b native_sim --build-dir=build_test -- \
+      #       -DDTC_OVERLAY_FILE=boards/native_sim.overlay \
+      #       -DEXTRA_CONF_FILE=test.prj.conf \
+      #       -DTEST_BUILD=ON
       
-      - name: Run unit tests
-        run: |
-          cd kernel_lab
-          chmod +x build_test/zephyr/zephyr.exe
-          build_test/zephyr/zephyr.exe | tee test_output.log
+      # - name: Run unit tests
+      #   run: |
+      #     cd lab_kernel
+      #     chmod +x build_test/zephyr/zephyr.exe
+      #     build_test/zephyr/zephyr.exe | tee test_output.log
           
-      - name: Check test results
-        run: |
-          cd kernel_lab
-          cat test_output.log
-          if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
-            echo "All tests passed!"
-            exit 0
-          elif grep -q "PROJECT EXECUTION FAILED" test_output.log; then
-            echo "Tests failed!"
-            exit 1
-          else
-            echo "Could not determine test status"
-            exit 1
-          fi
+      # - name: Check test results
+      #   run: |
+      #     cd lab_kernel
+      #     cat test_output.log
+      #     if grep -q "PROJECT EXECUTION SUCCESSFUL" test_output.log; then
+      #       echo "All tests passed!"
+      #       exit 0
+      #     elif grep -q "PROJECT EXECUTION FAILED" test_output.log; then
+      #       echo "Tests failed!"
+      #       exit 1
+      #     else
+      #       echo "Could not determine test status"
+      #       exit 1
+      #     fi
